Add first tech specs
gjgd/dont-slack-evil pull request #28
Opened 2020-03-01 15:57 UTC by Startouf

2020-03-02 02:30 UTC, gjgd approved these changes
LGTM 👍

2020-03-02 23:16 UTC, mourtisma approved these changes

2020-03-02 23:28 UTC, Startouf commented
Vous voulez merger dans le repo ou qu'on garde à côté ? on s'en parle pdt notre point de mercredi sinon

2020-03-04 12:46 UTC, gjgd requested changes
We said to move this to a Google doc

2020-03-04 16:33 UTC, closed without merging