Issue 16: User id to name
gjgd/dont-slack-evil pull request #37
Opened 2020-03-05 19:39 UTC by gjgd

- fixes #16: Implement translate user id to real name
- Move message specific code into switch case

2020-03-05 21:58 UTC, Startouf requested changes

2020-03-05 21:58 UTC, Startouf commented on apphome/apphome.go
> +func UserHome(name string) slack.Message {
Hey, je vais avoir besoin de garder le user ID. car j'en ai besoin pour aller récupérer les stats de la home.
Donc soit on laisse le userId ici et on le traduit après, soit on garde les 2 en interface

2020-03-05 21:58 UTC, Startouf commented on messages/main.go
> +					Blocks: apphome.UserHome(user.RealName).Blocks,
Donc garder le user ID ici pls :-)

2020-03-05 21:58 UTC, Startouf commented on messages/main.go
> +			user, getUserInfoErr := slackBotUserApiClient.GetUserInfo(homeOpened.User)
Je propose de déplacer ce code directement dans la UserHome

2020-03-06 08:18 UTC, mourtisma approved these changes

2020-03-07 16:40 UTC, gjgd commented
Too many conflicts, it's easier to close and reopen with a fresh copy of master

2020-03-07 16:40 UTC, closed without merging